databricks:
  DATABRICKS_SERVER_HOSTNAME : dbc-55a1270e-3e1b.cloud.databricks.com
  DATABRICKS_HTTP_PATH : sql/protocolv1/o/6624368804643013/1122-010506-r1raujkz
  DATABRICKS_TOKEN : dapi304cb9a1e3d03fb38e959cb151ac844f

mongodb:
  host: 13.229.93.144
  username: admin
  password: admin
  port: 27017
  connectTimeoutMS: 3000

trigger_conn:
  Databricks: true
  MongoDB: false
  MySQL: false
